### ISSUE TITLE
Release Q3 2023

### ISSUE THREAD

**Issue by 22388o** [AreaLayer/javascript-dlc#1]
**Pre  Beta**

- [x] Taproot implementation
- [x] LND/LDK integration
- [x] Finalize code via file LND.js , LDK.js , CLN.js and Eclair.js
- [x] DLCs events
- [x] Nostr integration
- [x] Core functions
- [x] Docs 
- [x] Testnet
- [x] JSON contracts example (WIP)
- [x] Package JSON 

**Beta**

- [x] Open source code
- [x] Announcement on Twitter, Telegram and Nostr
- [x] Taproot Channels (LND or LDK)

Detail: Release until end of 2023, if LND or LDK have Taproot channels already working:

- LDK: 

- [Part 1](https://github.com/lightningdevkit/rust-lightning/issues/2295)

- [Part.2](https://github.com/lightningdevkit/rust-lightning/pull/2289/)

- [LND](https://github.com/lightningnetwork/lnd/milestone/43)

**Comment by Rsync25** [comment]
Almost ready! :)
